[package]
name = "tcc"
version = "0.1.0"
authors = ["rot1024 <aayhrot@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
encoding_rs = "0.8.13"
encoding_rs_io = "0.1.3"
csv = "1.0.5"
